name: Build Openwrt

on:
  repository_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    name: ${{matrix.manufacturer}} ${{matrix.target}} ${{matrix.branch}}
    strategy:
      fail-fast: false
      matrix:
        branch: ["${{ github.event.client_payload.branch }}"]
        target: ["${{ github.event.client_payload.target }}"]
        manufacturer: ["${{ github.event.client_payload.manufacturer }}"]

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Load Settings.ini
      run: |
        source "${{matrix.manufacturer}}/devices/common/settings.ini"
        if [ -f "${{matrix.manufacturer}}/devices/${{matrix.target}}/settings.ini" ]; then
          source "${{matrix.manufacturer}}/devices/${{matrix.target}}/settings.ini"
        fi
        current_date=$(date +"%Y.%m.%d")
        echo "RELEASE_CODE=v${current_date}" >> $GITHUB_ENV
        echo "MY_BUILD_TARGET=${{matrix.target}}" >> $GITHUB_ENV
        echo "REPO_BRANCH=${{matrix.branch}}" >> $GITHUB_ENV
        echo "OP_MANUFACTURER=${{matrix.manufacturer}}" >> $GITHUB_ENV
        echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
        echo "CONFIG_FILE=${CONFIG_FILE}" >> $GITHUB_ENV
        echo "DIY_FEEDS_SH=${DIY_FEEDS_SH}" >> $GITHUB_ENV
        echo "DIY_P1_SH=${DIY_P1_SH}" >> $GITHUB_ENV
        echo "DIY_P2_SH=${DIY_P2_SH}" >> $GITHUB_ENV
        echo "UPLOAD_BIN_DIR=${UPLOAD_BIN_DIR}" >> $GITHUB_ENV
        echo "UPLOAD_FIRMWARE=${UPLOAD_FIRMWARE}" >> $GITHUB_ENV
        echo "UPLOAD_COWTRANSFER=${UPLOAD_COWTRANSFER}" >> $GITHUB_ENV
        echo "UPLOAD_WETRANSFER=${UPLOAD_WETRANSFER}" >> $GITHUB_ENV
        echo "UPLOAD_RELEASE=${UPLOAD_RELEASE}" >> $GITHUB_ENV
        
    - name: Trigger Packages Update
      run: |
        gitdate=$(curl -s "https://api.github.com/repos/zhuxiaole/OpenWrt-Packages/actions/runs" | jq -r '.workflow_runs[0].created_at')
        gitdate=$(date -d "$gitdate" +%s)
        now=$(date -d "$(date)" +%s)
        if [[ $(expr $gitdate + 300) < $now ]]; then
          curl -X POST https://api.github.com/repos/zhuxiaole/OpenWrt-Packages/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          --data '{"event_type": "update by build firmware", "client_payload": {"target": "${{ matrix.manufacturer }}"}}'
        fi

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds
      run: |
        cd openwrt
        chmod +x $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/common/$DIY_FEEDS_SH
        $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/common/$DIY_FEEDS_SH
        if [ -e $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_FEEDS_SH ]
        then
          chmod +x $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_FEEDS_SH
          $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_FEEDS_SH
        fi

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a
      
    - name: Load custom feeds packages
      run: |
        cd openwrt
        chmod +x $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/common/$DIY_P1_SH
        $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/common/$DIY_P1_SH
        if [ -e $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_P1_SH ]
        then
          chmod +x $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_P1_SH
          $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_P1_SH
        fi

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        if [ -e $OP_MANUFACTURER/devices/${{matrix.target}}/$CONFIG_FILE ]
        then
          mv -f $OP_MANUFACTURER/devices/${{matrix.target}}/$CONFIG_FILE openwrt/.config
        fi
        cd openwrt
        chmod +x $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/common/$DIY_P2_SH
        $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/common/$DIY_P2_SH
        if [ -e $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_P2_SH ]
        then
          chmod +x $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_P2_SH
          $GITHUB_WORKSPACE/$OP_MANUFACTURER/devices/${{matrix.target}}/$DIY_P2_SH
        fi
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: github.event.client_payload.test == 'true'
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: upload .config to WETRANSFER for test
      if: github.event.client_payload.test == 'true'
      run: |
        cd openwrt
        make defconfig
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress .config 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"

    - name: Download package
      id: package
      if: github.event.client_payload.test != 'true'
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      if: github.event.client_payload.test != 'true'
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: github.event.client_payload.test != 'true' && !cancelled()
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: github.event.client_payload.test != 'true' && env.UPLOAD_BIN_DIR == 'true' && steps.compile.outputs.status == 'success'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      if: github.event.client_payload.test != 'true' && env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: github.event.client_payload.test != 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Upload firmware to cowtransfer
      id: cowtransfer
      if: github.event.client_payload.test != 'true' && steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"

    - name: Upload firmware to WeTransfer
      id: wetransfer
      if: github.event.client_payload.test != 'true' && steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"

    - name: Generate release tag
      id: tag
      if: github.event.client_payload.test != 'true' && steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        release_tag="${{matrix.manufacturer}}|${{matrix.target}}|${{ env.RELEASE_CODE }}"
        release_name="${{matrix.manufacturer}} ${{matrix.target}} ${{ env.RELEASE_CODE }}"
        release_body="基于${{matrix.manufacturer}}-${{matrix.branch}}编译"
        echo "::set-output name=release_tag::${release_tag}"
        echo "::set-output name=release_name::${release_name}"
        echo "::set-output name=release_body::${release_body}"
        touch release.txt
        echo ${release_body} >> release.txt
        echo "::set-output name=status::success"
        
    - name: Remove same tag Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      if: github.event.client_payload.test != 'true' && steps.tag.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 0
        delete_tags: true
        delete_tag_pattern: ${{ steps.tag.outputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: github.event.client_payload.test != 'true' && steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        name: ${{ steps.tag.outputs.release_name }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
        
    - name: Prepare version information
      if: github.event.client_payload.test != 'true' && steps.tag.outputs.status == 'success' && !cancelled()
      run: |
        mkdir firmware_version
        cd firmware_version
        echo "latest_version:${{ env.RELEASE_CODE }}" > version.txt
        if [ "$(ls ${{ env.FIRMWARE }}/*squashfs-sysupgrade.bin 2> /dev/null | wc -l)" != "0" ]
        then
          download_url=$(curl -skfL "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.tag.outputs.release_tag }}" | jq -r '.assets[].browser_download_url' | sed -n "/squashfs-sysupgrade.bin/p")
        else
          if [ "$(ls ${{ env.FIRMWARE }}/*squashfs-combined.img.gz 2> /dev/null | wc -l)" != "0" ]
          then
            download_url=$(curl -skfL "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.tag.outputs.release_tag }}" | jq -r '.assets[].browser_download_url' | sed -n "/squashfs-combined.img.gz/p")
          else
            download_url=""
          fi
        fi
        if [ "$(ls ${{ env.FIRMWARE }}/*squashfs-combined-efi.img.gz 2> /dev/null | wc -l)" != "0" ]
        then
          efi_download_url=$(curl -skfL "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.tag.outputs.release_tag }}" | jq -r '.assets[].browser_download_url' | sed -n "/squashfs-combined-efi.img.gz/p")
        else
          efi_download_url=""
        fi
        if [ "${download_url}" != "" ]; then download_url="https://ghproxy.com/${download_url}"; fi
        if [ "${efi_download_url}" != "" ]; then efi_download_url="https://ghproxy.com/${efi_download_url}"; fi
        echo "download_url:${download_url}" >> version.txt
        echo "efi_download_url:${efi_download_url}" >> version.txt
        md5=$((md5sum ${{ env.FIRMWARE }}/*squashfs-sysupgrade* || md5sum ${{ env.FIRMWARE }}/*squashfs-combined.img*) | awk '{print $1}') 2>/dev/null
        efi_md5=$((md5sum ${{ env.FIRMWARE }}/*squashfs-combined-efi*) | awk '{print $1}') 2>/dev/null
        echo "md5:${md5}" >> version.txt
        echo "efi_md5:${efi_md5}" >> version.txt
        echo ${{ steps.tag.outputs.release_body }} > updatelogs.txt
        
    - name: Upload firmware version information
      if: github.event.client_payload.test != 'true' && steps.tag.outputs.status == 'success' && !cancelled()
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avzr --exclude="
        SOURCE: firmware_version/
        REMOTE_HOST: ${{ secrets.OP_SERVER_HOST }}
        REMOTE_PORT: ${{ secrets.OP_SERVER_PORT }}
        REMOTE_USER: root
        TARGET: "/data/openwrt/firmware/${{matrix.manufacturer}}/${{matrix.target}}/"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      continue-on-error: true
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 20
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
